name: 'coverage'

on:
  pull_request:
    branches:
      - main
  release:
    types: [created]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ArtiomTr/jest-coverage-report-action@v2
